name: Build and Test
on:
  - push

jobs:
  build-and-test-linux:
    strategy:
      fail-fast: true

    runs-on:
      - ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        name: install nix
        with:
          nix_path: nixpkgs=channel:nixos-23.05

      - name: make
        run: nix-shell --command 'make'

      - name: make test
        run: nix-shell --command 'make test'

      - name: run tests
        run: nix-shell --command 'bash run-tests.sh'

      - name: upload compiler binary
        uses: actions/upload-artifact@v2
        with:
          name: austral-linux-bin
          path: austral
          retention-days: 1

      - name: clean
        run: make clean

      - name: assert executable does not exist
        run: test ! -f austral
